import type { Metadata } from "next";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_components/Nav";
import Footer from "./_components/Footer";
import NextauthProvider from "@/provider/component/Nextauth.provider";
import ReactQueryProviders from "@/provider/component/ReactQuery.provider";
import { Toaster } from "react-hot-toast";
import { ForgetProvider } from "./context/ForgetContext";
import { ThemeProvider } from "./context/Theme";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ReactQueryProviders>
          <Toaster />
          <ThemeProvider>
            <ForgetProvider>
              <NextauthProvider>
                <div className={`flex flex-col justify-between min-h-screen lightt`}>
                  <Nav />
                  <div className="container min-h-screen scroll-pt-16 ">
                    {children}
                  </div>
                  <Footer />
                </div>
              </NextauthProvider>
            </ForgetProvider>
          </ThemeProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
